"""Added delivery_timing column to Courier

Revision ID: c7f90b64abcd
Revises: 
Create Date: 2025-01-19 20:31:24.318507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f90b64abcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale')
    with op.batch_alter_table('courier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_timing', sa.Enum('ON_TIME', 'LATE', 'NOT_DELIVERED', name='deliverytimingstatus'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courier', schema=None) as batch_op:
        batch_op.drop_column('delivery_timing')

    op.create_table('sale',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_of_sale', sa.VARCHAR(length=10), nullable=False),
    sa.Column('units_sold', sa.INTEGER(), nullable=False),
    sa.Column('total_revenue', sa.FLOAT(), nullable=False),
    sa.Column('profit_or_loss', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
